(require 'dired+)
(require 'paren)
(require 'nav)
(require 'ido)
(require 'smex)
(require 'autopair)
(require 'org)
(require 'yasnippet)
(require 'auto-highlight-symbol)
(require 'highlight-symbol)

(provide 'baoduy/load-package)
