(require 'package)
;; loading command `emacsclient -e "(run-C-C++-IDE-other-process)"`
(cond
 ((string= "CEDET" work-mode) 
  (print "load cedet space")
  (require 'baoduy/cedet-config))
 ((string= "C/C++ IDE" work-mode)
  (print "My setup for C/C++ development")
  (require 'baoduy/c-c++-ide-config))
 ((string= "ORG" work-mode) 
  (print "load cedet space")
  (require 'baoduy/org-config))
 ((string= "JAVA" work-mode) 
  (print "load JAVA IDE space")
  (require 'baoduy/java-config))
 ((string= "ANDROID" work-mode) 
  (print "load cedet space")
  (require 'baoduy/android-config))
 ((string= "ELISP" work-mode) 
  (print "load cedet space")
  (require 'baoduy/elisp-config))
 ((string= "SCHEME" work-mode) 
  (print "load cedet space")
  (require 'baoduy/scheme-config))
 ((string= "CLOJURE" work-mode)
  (print "My setup for clojure environment")
  (require 'baoduy/clojure-config))
 (t 
  (print "Load default space")
  (setq frame-title-format
        (list (format "COMMON@%s %%S: %%j " (system-name))
              '(buffer-file-name "%f" (dired-directory dired-directory "%b"))))
  (server-start))
 )

(require 'baoduy/cusFunc)

(provide 'baoduy)
