# Automatically Generated Makefile by EDE.
# For use with: make
# Relative File Name: Makefile
#
# DO NOT MODIFY THIS FILE OR YOUR CHANGES MAY BE LOST.
# EDE is the Emacs Development Environment.
# http://cedet.sourceforge.net/ede.shtml
#
require=$(foreach r,$(1),(require (quote $(r))))
EMACSFLAGS=-batch --no-site-file --eval '(setq debug-on-error t)' -l "../../cedet-remove-builtin.el"
EMACS=@echo "    > $@";emacs
AUTOGENFLAGS=-L . --eval '(progn (require (quote cedet-compat)) (require (quote mode-local)))'

top=
ede_FILES=Project.ede Makefile

test_LISP=init.el ui.el cui.el cusFunc.el baoduy.el ede-projects.el
LOADPATH= ../c_dev_el/emacs/lisp/
VERSION=0.1dev
DISTDIR=$(top)dotEmacs-$(VERSION)



all: test

%.elc: %.el
	$(EMACS) $(EMACSFLAGS) $(addprefix -L ,$(LOADPATH)) --eval '(progn $(call require, $(PRELOADS)))' -f batch-byte-compile $^

.PHONY: test
test: $(addsuffix c, $(test_LISP))
test: PRELOADS=

tags: 


clean:
	rm -f *.elc

.PHONY: dist

dist:
	mkdir $(DISTDIR)
	cp $(test_LISP) $(ede_FILES) $(DISTDIR)

Makefile: Project.ede
	@echo Makefile is out of date!  It needs to be regenerated by EDE.
	@echo If you have not modified Project.ede, you can use 'touch' to update the Makefile time stamp.
	@false



# End of Makefile
